weights: yolov5m.pt
cfg: /content/drive/MyDrive/TZ/epoch8/yolov5m.yaml
data: /content/drive/MyDrive/TZ/epoch8/data_config.yaml
hyp: data/hyp.scratch.yaml
epochs: 150
batch_size: 9
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: runs/train
entity: null
name: /content/drive/MyDrive/TZ/epoch8/model_yolo/yolov5m_parrot
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
world_size: 1
global_rank: -1
save_dir: /content/drive/MyDrive/TZ/epoch8/model_yolo/yolov5m_parrot8
total_batch_size: 9
